"""Dev-only: extract fitted BKT parameters and build the Node parity fixture.

Never deployed (Req 10.1). Python standard library only.

Usage:
    python scripts/amBktExtract.py --module <checkout>/modules/diagnostic-skillgps

Reads from the module checkout:
    ml/dsmodel.pkl            fitted BKT Model_Bundle (plain dicts, pickle.load)
    ml/dsbkt.py               BKT reference implementation
    ml/dstest_sequences.csv   held-out sequences
    supabase/dsseed.sql       topic names in insertion order

Writes (relative to this repo):
    shared/amBktParams.js           AM_BKT_DEFAULT + frozen AM_BKT_SKILLS keyed by topic_name
    tests/fixtures/amBktParity.json reference results from dsbkt.run_sequence /
                                    dsbkt.build_prediction_result
"""

from __future__ import annotations

import argparse
import csv
import importlib
import json
import math
import pickle
import random
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PARAMS_OUT = REPO_ROOT / "shared" / "amBktParams.js"
PARITY_OUT = REPO_ROOT / "tests" / "fixtures" / "amBktParity.json"

PARAM_NAMES = ("p_init", "p_transit", "p_slip", "p_guess")
EXPECTED_SKILLS = 49
EXPECTED_HELD_OUT = 720
RANDOM_CASES = 300
DEFAULT_CASES = 20
MAX_LEN = 20
SEED = 20240611


def fail(message: str) -> None:
    raise SystemExit(f"amBktExtract: {message}")


def check_params(label: str, params: dict) -> dict:
    """Assert the four params exist, are finite in [0, 1], and slip + guess < 1."""
    if not isinstance(params, dict):
        fail(f"{label}: params must be a dict")
    out = {}
    for name in PARAM_NAMES:
        value = params.get(name)
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            fail(f"{label}.{name}: not a number ({value!r})")
        value = float(value)
        if not math.isfinite(value) or not (0.0 <= value <= 1.0):
            fail(f"{label}.{name}: out of [0, 1] ({value!r})")
        out[name] = value
    if not out["p_slip"] + out["p_guess"] < 1.0:
        fail(f"{label}: p_slip + p_guess must be < 1")
    return out


def load_bundle(ml_dir: Path) -> dict:
    with (ml_dir / "dsmodel.pkl").open("rb") as fh:
        bundle = pickle.load(fh)
    if not isinstance(bundle, dict):
        fail("dsmodel.pkl: expected a dict bundle")
    if bundle.get("engine") != "bkt":
        fail(f"dsmodel.pkl: engine must be 'bkt' (got {bundle.get('engine')!r})")
    skills = bundle.get("skill_params")
    if not isinstance(skills, dict) or len(skills) != EXPECTED_SKILLS:
        fail(f"dsmodel.pkl: expected {EXPECTED_SKILLS} skills")
    expected_keys = {str(k) for k in range(1, EXPECTED_SKILLS + 1)}
    if set(map(str, skills.keys())) != expected_keys:
        fail("dsmodel.pkl: skill keys must be '1'..'49'")
    return bundle


def parse_topic_names(seed_sql: Path) -> list[str]:
    """Return topic names from every `insert into public.topics` block, in order."""
    text = seed_sql.read_text(encoding="utf-8")
    block_re = re.compile(
        r"insert\s+into\s+public\.topics\s*\(\s*subject_id\s*,\s*topic_name\s*,\s*description\s*\)\s*values"
        r"(.*?)on\s+conflict",
        re.IGNORECASE | re.DOTALL,
    )
    row_re = re.compile(r"\(\s*v_subject_id\s*,\s*'((?:[^']|'')*)'")
    names: list[str] = []
    for block in block_re.finditer(text):
        for row in row_re.finditer(block.group(1)):
            names.append(row.group(1).replace("''", "'"))
    if len(names) != EXPECTED_SKILLS or len(set(names)) != EXPECTED_SKILLS:
        fail(f"dsseed.sql: expected {EXPECTED_SKILLS} unique topic names (got {len(names)})")
    return names


def js_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def js_params(params: dict) -> str:
    return ", ".join(f"{name}: {params[name]!r}" for name in PARAM_NAMES)


def write_params_js(bundle: dict, default: dict, skills: dict, names: list[str]) -> None:
    lines = [
        "// Generated by scripts/amBktExtract.py from ml/dsmodel.pkl "
        f"(engine={bundle['engine']}, fit_method={bundle.get('fit_method')}, "
        f"{bundle.get('skills_fit_by_em')}/{bundle.get('skills_total')} skills). Do not edit.",
        f"export const AM_BKT_DEFAULT = Object.freeze({{ {js_params(default)} }});",
        "export const AM_BKT_SKILLS = Object.freeze({",
    ]
    for k, name in enumerate(names, start=1):
        key = str(k)
        lines.append(
            f"  {js_str(name)}: Object.freeze({{ skillKey: {js_str(key)}, {js_params(skills[key])} }}),"
        )
    lines.append("});")
    PARAMS_OUT.parent.mkdir(parents=True, exist_ok=True)
    PARAMS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def load_held_out(csv_path: Path) -> list[tuple[int, list[bool]]]:
    """Group rows by (student_id, topic_id) in first-seen order, sorted by sequence_index."""
    groups: dict[tuple[str, int], list[tuple[int, bool]]] = {}
    with csv_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            key = (row["student_id"], int(row["topic_id"]))
            value = row["is_correct"].strip()
            if value not in ("0", "1"):
                fail(f"dstest_sequences.csv: bad is_correct {value!r}")
            groups.setdefault(key, []).append((int(row["sequence_index"]), value == "1"))
    out = []
    for (_, topic_id), rows in groups.items():
        rows.sort(key=lambda r: r[0])
        out.append((topic_id, [correct for _, correct in rows]))
    if len(out) != EXPECTED_HELD_OUT:
        fail(f"dstest_sequences.csv: expected {EXPECTED_HELD_OUT} sequences (got {len(out)})")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--module", required=True, help="path to modules/diagnostic-skillgps")
    args = parser.parse_args()

    module_dir = Path(args.module).resolve()
    ml_dir = module_dir / "ml"
    sys.path.insert(0, str(ml_dir))
    dsbkt = importlib.import_module("dsbkt")

    bundle = load_bundle(ml_dir)
    default = check_params("default_params", bundle.get("default_params"))
    if default != dsbkt.DEFAULT_PARAMS.as_dict():
        fail("default_params differ from dsbkt.DEFAULT_PARAMS")
    skills = {str(k): check_params(f"skill {k}", v) for k, v in bundle["skill_params"].items()}
    names = parse_topic_names(module_dir / "supabase" / "dsseed.sql")

    write_params_js(bundle, default, skills, names)

    skill_bkt = {key: dsbkt.BKTParams.from_mapping(p) for key, p in skills.items()}
    default_bkt = dsbkt.BKTParams.from_mapping(default)

    def entry(topic_name, responses, params):
        mastery = dsbkt.run_sequence(responses, params)
        result = dsbkt.build_prediction_result(mastery)
        return {
            "topicName": topic_name,
            "responses": list(responses),
            "mastery_probability": result["mastery_probability"],
            "probabilities": result["probabilities"],
        }

    entries = []
    held_out = load_held_out(ml_dir / "dstest_sequences.csv")
    held_topics = set()
    for topic_id, responses in held_out:
        key = str(topic_id)
        if key not in skill_bkt:
            fail(f"dstest_sequences.csv: unknown topic_id {topic_id}")
        held_topics.add(key)
        entries.append(entry(names[topic_id - 1], responses, skill_bkt[key]))
    if len(held_topics) != EXPECTED_SKILLS:
        fail(f"dstest_sequences.csv: expected all {EXPECTED_SKILLS} topics (got {len(held_topics)})")

    rng = random.Random(SEED)
    for _ in range(RANDOM_CASES):
        k = rng.randint(1, EXPECTED_SKILLS)
        responses = [rng.random() < 0.5 for _ in range(rng.randint(1, MAX_LEN))]
        entries.append(entry(names[k - 1], responses, skill_bkt[str(k)]))
    for _ in range(DEFAULT_CASES):
        responses = [rng.random() < 0.5 for _ in range(rng.randint(1, MAX_LEN))]
        entries.append(entry(None, responses, default_bkt))

    fixture = {
        "generatedBy": "scripts/amBktExtract.py",
        "seed": SEED,
        "counts": {"heldOut": len(held_out), "random": RANDOM_CASES, "default": DEFAULT_CASES},
        "entries": entries,
    }
    PARITY_OUT.parent.mkdir(parents=True, exist_ok=True)
    # json.dumps writes floats with repr, so full precision is kept.
    PARITY_OUT.write_text(json.dumps(fixture, indent=1) + "\n", encoding="utf-8", newline="\n")

    print(f"wrote {PARAMS_OUT.relative_to(REPO_ROOT)} ({len(names)} skills)")
    print(f"wrote {PARITY_OUT.relative_to(REPO_ROOT)} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
